# Generated by Django 4.1.2 on 2022-10-05 23:41

import almacen.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, validators=[almacen.validators.validar_nombre_categoria]),
        ),
    ]
