# Generated by Django 4.1.2 on 2022-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo_almacen',
            name='cantidad',
            field=models.BigIntegerField(default=0),
        ),
    ]
