# Generated by Django 4.1.2 on 2022-10-07 03:24

import almacen.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_articulo_almacen_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(max_length=50, validators=[almacen.validators.validar_nombres]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.TextField(validators=[almacen.validators.validar_nombres]),
        ),
        migrations.AlterField(
            model_name='articulo_almacen',
            name='cantidad',
            field=models.BigIntegerField(default=1, validators=[almacen.validators.validar_cantidad_articulo_almacen]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, validators=[almacen.validators.validar_proveedor]),
        ),
    ]
