# Generated by Django 4.1.2 on 2022-10-07 15:59

import almacen.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_almacen_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=50, validators=[almacen.validators.validar_nombres]),
        ),
    ]
